const SET_AUTH = 'SET_AUTH'
const CLEAR_AUTH = 'CLEAR_AUTH'
const GET_QUESTIONS = 'GET_QUESTIONS'
const GET_QUESTION = 'GET_QUESTION'
const ADD_QUESTION = 'ADD_QUESTION'
const ADD_ANSWER = 'ADD_ANSWER'
const UPDATE_ANSWER = 'UPDATE_ANSWER'
const UPDATE_QUESTION_VOTES = 'UPDATE_QUESTION_VOTES'
const CLEAR_SELECT = 'CLEAR_SELECT'

export default {
  SET_AUTH,
  CLEAR_AUTH,
  GET_QUESTIONS,
  GET_QUESTION,
  ADD_QUESTION,
  ADD_ANSWER,
  UPDATE_ANSWER,
  UPDATE_QUESTION_VOTES,
  CLEAR_SELECT
}
